name: coa_classifier
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.8.12
  - zodb=5.6
  - numpy=1.19
  - pyyaml=5.4.1
  - ca-certificates
  - certifi
  - openssl
  - jinja2=3.0
  - seaborn=0.11.2
  - scikit-learn==1.0
  - joblib
  - snakemake==5.26.1
  - cudatoolkit=10.2
  - tensorflow-gpu
  - pip:
    - pyabf

