#########################################
#      CONVOLUTIONAL NEURAL NETWORK     #
#            PARAMETER FILE             #
#########################################


# CNN ARCHITECTURE
nn_class: Cnn_test
batch_norm: 0
batch_size: 32
dropout_keep_prob: 0.9
max_sequence_length: 10000
eps_per_kmer_switch: 25
filter_width: 500
filters: 5
kernel_size: 19
learning_rate: 0.002
num_batches: 320
num_kmer_switches: 1
num_layers: 2
pool_size: 8 # Pool size to use for 1d maxpool
threshold: 0.0

