#########################################
#      CONVOLUTIONAL NEURAL NETWORK     #
#            PARAMETER FILE             #
#########################################


# CNN ARCHITECTURE
nn_class: Cnn
batch_norm: 1
batch_size: 16
dropout_keep_prob: 0.85
eps_per_kmer_switch: 500
filter_width: 500
filters: 10
kernel_size: 25
learning_rate: 0.0001
max_sequence_length: 15000
num_batches: 96
num_kmer_switches: 1
num_layers: 3
pool_size: 12

# --- COMPILED MODEL PARAMS ---
threshold: 0
