#########################################
#      CONVOLUTIONAL NEURAL NETWORK     #
#            PARAMETER FILE             #
#########################################

# Just built this to do some more messing about

# CNN ARCHITECTURE
nn_class: Cnn_test
batch_norm: 0
batch_size: 32
dropout_keep_prob: 0.75
eps_per_kmer_switch: 30
max_sequence_length: 15000
filter_width: 250
filters: 6
kernel_size: 19
learning_rate: 0.001
num_batches: 320
num_kmer_switches: 1
num_layers: 4
pool_size: 8 # Pool size to use for 1d maxpool
threshold: 0.0
