#########################################
#      CONVOLUTIONAL NEURAL NETWORK     #
#            PARAMETER FILE             #
#########################################


# CNN ARCHITECTURE
nn_class: Cnn_test
batch_norm: 1
batch_size: 16
dropout_keep_prob: 0.8
eps_per_kmer_switch: 250
filter_width: 250
filters: 10
kernel_size: 25
learning_rate: 0.001
max_sequence_length: 15000
num_batches: 96
num_kmer_switches: 1
num_layers: 2
pool_size: 10

# --- COMPILED MODEL PARAMS ---
threshold: 0
