#########################################
#      CONVOLUTIONAL NEURAL NETWORK     #
#            PARAMETER FILE             #
#########################################


# CNN ARCHITECTURE
nn_class: Cnn
batch_norm: 1
batch_size: 32
dropout_keep_prob: 0.8
eps_per_kmer_switch: 25
filter_width: 250
filters: 10
kernel_size: 25
learning_rate: 0.002
max_sequence_length: 15000
num_batches: 96
num_kmer_switches: 20
num_layers: 2
pool_size: 12
oversampling: True

# --- COMPILED MODEL PARAMS ---
threshold: 6.21
filter_stride: 125
k_frac: 0.65
