#########################################
#      CONVOLUTIONAL NEURAL NETWORK     #
#            PARAMETER FILE             #
#########################################


# CNN ARCHITECTURE
nn_class: Cnn
batch_norm: 1
batch_size: 16
dropout_keep_prob: 0.8
epochs: 50
filter_width: 50000
filters: 10
kernel_size: 25
learning_rate: 0.001
num_layers: 2
pool_size: 10
oversampling: True

