#########################################
# BIDIRECTIONAL RECURRENT NEURAL NETWORK#
#            PARAMETER FILE             #
#########################################

# RNN ARCHITECTURE
nn_class: Rnn_keras
batch_size: 32
num_batches: 320
eps_per_kmer_switch: 20
num_layers: 2
max_sequence_length: 10000  # Only for example reads
cell_type: GRU
layer_size: 16
name_optimizer: adam
learning_rate: 0.001
num_kmer_switches: 10
dropout_keep_prob: 0.5
threshold: 0.95
filter_width: 1000
